name: skript-logs
description: An addon to listen to log messages in Skript. And more!
version: @version@

author: Blueyescat
website: https://github.com/Blueyescat/skript-logs

depend: [Skript]

main: me.blueyescat.skriptlogs.SkriptLogs
api-version: 1.13
